//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSHM.Presentation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSHM.Presentation.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این شماره حساب بسته شده است.
        /// </summary>
        public static string AccountNumberIsClosed {
            get {
                return ResourceManager.GetString("AccountNumberIsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره حساب توسط بانک غیرفعال شده است.
        /// </summary>
        public static string AccountNumberIsDeactive {
            get {
                return ResourceManager.GetString("AccountNumberIsDeactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع حساب ناشناخته می باشد.
        /// </summary>
        public static string AccountTypeUnknown {
            get {
                return ResourceManager.GetString("AccountTypeUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان تراکنش با مبلغ صفر ریال امکانپذیر نمی باشد.
        /// </summary>
        public static string Amount0NotValid {
            get {
                return ResourceManager.GetString("Amount0NotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رشته کاربری معتبر نمی باشد.
        /// </summary>
        public static string ApiKeyNotFound {
            get {
                return ResourceManager.GetString("ApiKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرایط پل احراز نشد.
        /// </summary>
        public static string BridgeRulesNotValid {
            get {
                return ResourceManager.GetString("BridgeRulesNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد امنیتی صحیح نمی باشد.
        /// </summary>
        public static string CaptchaFailed {
            get {
                return ResourceManager.GetString("CaptchaFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تلفن همراه معتبر نمی باشد.
        /// </summary>
        public static string CellphoneNotValid {
            get {
                return ResourceManager.GetString("CellphoneNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شارژ جیب با شکست مواجه شد.
        /// </summary>
        public static string ChargeFailed {
            get {
                return ResourceManager.GetString("ChargeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شارژ جیب با موفقیت انجام شد.
        /// </summary>
        public static string ChargeSuccessed {
            get {
                return ResourceManager.GetString("ChargeSuccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قرارداد هم پیمانی منقضی شده است.
        /// </summary>
        public static string CofederationExpired {
            get {
                return ResourceManager.GetString("CofederationExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال به هم پیمان با شکست مواجه شد.
        /// </summary>
        public static string CofederationFailed {
            get {
                return ResourceManager.GetString("CofederationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال به هم پیمان با موفقیت انجام شد.
        /// </summary>
        public static string CofederationSuccessed {
            get {
                return ResourceManager.GetString("CofederationSuccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان استفاده ازحساب مشترک در کیف پول ممنوعیت دارد.
        /// </summary>
        public static string CommonAccountIsForbidden {
            get {
                return ResourceManager.GetString("CommonAccountIsForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سقف تعداد تراکنش روزانه این جیب تکمیل شده است.
        /// </summary>
        public static string CountTransactionDailyRejected {
            get {
                return ResourceManager.GetString("CountTransactionDailyRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سقف تعداد تراکنش ماهیانه این جیب تکمیل شده است.
        /// </summary>
        public static string CountTransactionMonthlyRejected {
            get {
                return ResourceManager.GetString("CountTransactionMonthlyRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد کاربر جدید توسط مرکز محدود شده است.
        /// </summary>
        public static string CreateUserDenied {
            get {
                return ResourceManager.GetString("CreateUserDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت کاربری با خطا مواجه شد.
        /// </summary>
        public static string CreateUserFailed {
            get {
                return ResourceManager.GetString("CreateUserFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد کیف پول با مشکل مواجه گردید.
        /// </summary>
        public static string CreateWalletFailed {
            get {
                return ResourceManager.GetString("CreateWalletFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدم همخوانی کاربران تراکنش.
        /// </summary>
        public static string CreatorTransactionDenied {
            get {
                return ResourceManager.GetString("CreatorTransactionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این کاربر فاقد شماره مشتری در بانک می باشد.
        /// </summary>
        public static string CustomerNumberNotFound905 {
            get {
                return ResourceManager.GetString("CustomerNumberNotFound905", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سقف واریز روزانه به جیب مقصد رعایت نشده است.
        /// </summary>
        public static string DepositDailyRejected {
            get {
                return ResourceManager.GetString("DepositDailyRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سقف واریز ماهیانه به جیب مقصد رعایت نشده است.
        /// </summary>
        public static string DepositMonthlyRejected {
            get {
                return ResourceManager.GetString("DepositMonthlyRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سقف واریز کل به جیب مقصد رعایت نشده است.
        /// </summary>
        public static string DepositTotalRejected {
            get {
                return ResourceManager.GetString("DepositTotalRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کیف پول مقصد یافت نشد.
        /// </summary>
        public static string DestinationWalletNotFound {
            get {
                return ResourceManager.GetString("DestinationWalletNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 605.
        /// </summary>
        public static string Error605 {
            get {
                return ResourceManager.GetString("Error605", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 610.
        /// </summary>
        public static string Error610 {
            get {
                return ResourceManager.GetString("Error610", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 930.
        /// </summary>
        public static string Error930 {
            get {
                return ResourceManager.GetString("Error930", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 931.
        /// </summary>
        public static string Error931 {
            get {
                return ResourceManager.GetString("Error931", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای فرآیند کسب و کار.
        /// </summary>
        public static string ErrorInBusiness {
            get {
                return ResourceManager.GetString("ErrorInBusiness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یک استثنای درونی بوجود آمده است.
        /// </summary>
        public static string ExceptionRaised {
            get {
                return ResourceManager.GetString("ExceptionRaised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اقلام اطلاعاتی مورد نیاز کامل نیستند.
        /// </summary>
        public static string FiledsNotCompleted {
            get {
                return ResourceManager.GetString("FiledsNotCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پسوند درونی فایل {0}  نامعتبر می باشد.
        /// </summary>
        public static string FileMatcherIsNotValid {
            get {
                return ResourceManager.GetString("FileMatcherIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فایل پیوست یافت نشد.
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جیب مبدا یافت نشد.
        /// </summary>
        public static string FromPocketNotFound {
            get {
                return ResourceManager.GetString("FromPocketNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درگاه پرداخت توسط ادمین کل بسته شده است.
        /// </summary>
        public static string GatewayIsClosed {
            get {
                return ResourceManager.GetString("GatewayIsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سقف تراکنش در درگاه پرداخت رعایت نشده است.
        /// </summary>
        public static string GatewayMaxTransactionIsNotValid {
            get {
                return ResourceManager.GetString("GatewayMaxTransactionIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیام رمزشده درگاه پرداخت نامعتبر است.
        /// </summary>
        public static string GatewayPostMessageFailed {
            get {
                return ResourceManager.GetString("GatewayPostMessageFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرآیند بازگشایی پیام رمزشده درگاه پرداخت با موفقت پایان یافت.
        /// </summary>
        public static string GatewayPostMessageSuccessed {
            get {
                return ResourceManager.GetString("GatewayPostMessageSuccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرایط اعطای هدیه به کاربر میسر نمی باشد.
        /// </summary>
        public static string GiftRulesNotValid {
            get {
                return ResourceManager.GetString("GiftRulesNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع هدیه نامشخص می باشد.
        /// </summary>
        public static string GiftTypeNotValid {
            get {
                return ResourceManager.GetString("GiftTypeNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فزآیند استعلام با شکست مواجه شد.
        /// </summary>
        public static string InquiryFailed {
            get {
                return ResourceManager.GetString("InquiryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرآیند استعلام با موفقیت انجام شد.
        /// </summary>
        public static string InquirySuccess {
            get {
                return ResourceManager.GetString("InquirySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موجودی جیب ناکافی است.
        /// </summary>
        public static string LessBalancePocket {
            get {
                return ResourceManager.GetString("LessBalancePocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موجودی این صورتحساب ناکافی است.
        /// </summary>
        public static string LessBalanceVoucher {
            get {
                return ResourceManager.GetString("LessBalanceVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سقف تراکنش رعایت  نشده است.
        /// </summary>
        public static string MaxPerTransactionRejected {
            get {
                return ResourceManager.GetString("MaxPerTransactionRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پذیرنده فاقد دسترسی به کیف پول مقصد می باشد.
        /// </summary>
        public static string MerchantAccessForbidden {
            get {
                return ResourceManager.GetString("MerchantAccessForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پذیرنده یافت نشد.
        /// </summary>
        public static string MerchantNotFound {
            get {
                return ResourceManager.GetString("MerchantNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل مانده  {0}  ریال می باشد.
        /// </summary>
        public static string MinAfterCharge {
            get {
                return ResourceManager.GetString("MinAfterCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل شارژ  {0}  ریال می‌باشد.
        /// </summary>
        public static string MinChargeRejected {
            get {
                return ResourceManager.GetString("MinChargeRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدم تطابق شماره حساب و کدملی در سمت بانک.
        /// </summary>
        public static string NIDNotMatchWithAccountNumber {
            get {
                return ResourceManager.GetString("NIDNotMatchWithAccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد/شناسه ملی معتبر نمی باشد.
        /// </summary>
        public static string NIDNotValid {
            get {
                return ResourceManager.GetString("NIDNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز پویا برای کاربر جاری به مدت 5 دقیقه شده است.
        /// </summary>
        public static string OTPBlocked {
            get {
                return ResourceManager.GetString("OTPBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز یکبارمصرف نامعتبر است.
        /// </summary>
        public static string OTPFailed {
            get {
                return ResourceManager.GetString("OTPFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اقلام رمز پویا با انبار داده مطابقت ندارد.
        /// </summary>
        public static string OTPFieldsNotMatched {
            get {
                return ResourceManager.GetString("OTPFieldsNotMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد رمز پویا با شکست مواجه شد.
        /// </summary>
        public static string OTPGenerationFailed {
            get {
                return ResourceManager.GetString("OTPGenerationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز یکبار مصرف قبلا استفاده شده است..
        /// </summary>
        public static string OTPIsUsed {
            get {
                return ResourceManager.GetString("OTPIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز پویا کمتر از 90 ثانیه پیش درخواست شده است.
        /// </summary>
        public static string OTPLastSentError {
            get {
                return ResourceManager.GetString("OTPLastSentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز پویا در انبار داده یافت نشد.
        /// </summary>
        public static string OTPNotInRedis {
            get {
                return ResourceManager.GetString("OTPNotInRedis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال رمز پویا با شکست مواجه شد.
        /// </summary>
        public static string OTPNotSent {
            get {
                return ResourceManager.GetString("OTPNotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این جیب یا وجود ندارد یا شما مجاز به دسترسی به آن نمی باشید.
        /// </summary>
        public static string PocketAccessDenied {
            get {
                return ResourceManager.GetString("PocketAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جیب مورد نظر یافت نشد.
        /// </summary>
        public static string PocketNotFound {
            get {
                return ResourceManager.GetString("PocketNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جیب طرف دوم حساب یافت نشد.
        /// </summary>
        public static string PocketToNotFound {
            get {
                return ResourceManager.GetString("PocketToNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این رکورد موجود نمی باشد.
        /// </summary>
        public static string RecordNotFound {
            get {
                return ResourceManager.GetString("RecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای صورتحساب {VoucherNumber} در گذشته استرداد وجه ثبت شده است.
        /// </summary>
        public static string RepetitiveRefund {
            get {
                return ResourceManager.GetString("RepetitiveRefund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یکسان بودن شناسه جیب مبدا و مقصد مجاز نمی باشد.
        /// </summary>
        public static string SamePocketForbidden {
            get {
                return ResourceManager.GetString("SamePocketForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلید محرمانه معتبر نمی باشد.
        /// </summary>
        public static string SecretKeyNotValid {
            get {
                return ResourceManager.GetString("SecretKeyNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سرویس مورد نظر فعال نمی باشد.
        /// </summary>
        public static string ServiceUnavailable {
            get {
                return ResourceManager.GetString("ServiceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات ادمین مانع از انجام این فرآیند است.
        /// </summary>
        public static string SettingFailed {
            get {
                return ResourceManager.GetString("SettingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات یافت نشد.
        /// </summary>
        public static string SettingNotFound {
            get {
                return ResourceManager.GetString("SettingNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب تسویه یافت نشد.
        /// </summary>
        public static string SettleAccountNotFound {
            get {
                return ResourceManager.GetString("SettleAccountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کیف پول مبدا یافت نشد.
        /// </summary>
        public static string SourceWalletNotFound {
            get {
                return ResourceManager.GetString("SourceWalletNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ترمینال یافت نشد.
        /// </summary>
        public static string TerminalNotFound {
            get {
                return ResourceManager.GetString("TerminalNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پایانه معتبر نمی باشد.
        /// </summary>
        public static string TerminalNotValid {
            get {
                return ResourceManager.GetString("TerminalNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جیب مقصد یافت نشد.
        /// </summary>
        public static string ToPocketNotFound {
            get {
                return ResourceManager.GetString("ToPocketNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرایط تراکنش محقق نشد.
        /// </summary>
        public static string TransactionConditionsDenied {
            get {
                return ResourceManager.GetString("TransactionConditionsDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما مجوز دسترسی به این تراکنش را ندارید.
        /// </summary>
        public static string TransactionDenied {
            get {
                return ResourceManager.GetString("TransactionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تراکنش {TransactionTypeID} با شکست مواجه شد.
        /// </summary>
        public static string TransactionFailed {
            get {
                return ResourceManager.GetString("TransactionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تراکنش در هسته متمرکز مهرگستر با شکست مواجه شد.
        /// </summary>
        public static string TransactionFailedInVIPC {
            get {
                return ResourceManager.GetString("TransactionFailedInVIPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این تراکنش برای جیب مورد نظر تعریف نشده است.
        /// </summary>
        public static string TransactionPocketTypeNotFound {
            get {
                return ResourceManager.GetString("TransactionPocketTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع تراکنش ارسالی، توسط ادمین پلتفرم غیرفعال شده است.
        /// </summary>
        public static string TransactionTypeDeactivated {
            get {
                return ResourceManager.GetString("TransactionTypeDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع تراکنش نامعتبر است.
        /// </summary>
        public static string TransactionTypeInvalid {
            get {
                return ResourceManager.GetString("TransactionTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات انتقال وجه در هسته متمرکز بانکداری با شکست مواجه شد.
        /// </summary>
        public static string TransferAccountToAccountFailed {
            get {
                return ResourceManager.GetString("TransferAccountToAccountFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات انتقال وجه با موفقیت انجام شد.
        /// </summary>
        public static string TransferAccountToAccountSuccessed {
            get {
                return ResourceManager.GetString("TransferAccountToAccountSuccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتقال وجه با شکست مواجه شد.
        /// </summary>
        public static string TransferFailed {
            get {
                return ResourceManager.GetString("TransferFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتقال وجه با موفقیت صورت پذیرفت.
        /// </summary>
        public static string TransferSuccessed {
            get {
                return ResourceManager.GetString("TransferSuccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع شارژ ناشناخته است.
        /// </summary>
        public static string UnknownChargeType {
            get {
                return ResourceManager.GetString("UnknownChargeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بروزرسانی با شکست مواجه گردید.
        /// </summary>
        public static string UpdateFailed {
            get {
                return ResourceManager.GetString("UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره حساب کاربر یافت نشد.
        /// </summary>
        public static string UserAccountNotFound {
            get {
                return ResourceManager.GetString("UserAccountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این شماره حساب در کیف پول ثبت نشده است.
        /// </summary>
        public static string UserAccountNotRegistered {
            get {
                return ResourceManager.GetString("UserAccountNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربری ایجاد شد اما در ساخت کیف پول با مشکل مواجه گردید.
        /// </summary>
        public static string UserCreatedButWalletFailed {
            get {
                return ResourceManager.GetString("UserCreatedButWalletFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این کدملی قبلا ثبت شده است.
        /// </summary>
        public static string UserExist {
            get {
                return ResourceManager.GetString("UserExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقطه اتصال کاربر معتبر نمی باشد.
        /// </summary>
        public static string UserGaurdNotValid {
            get {
                return ResourceManager.GetString("UserGaurdNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این نقش قبلا به این کاربر نسبت داده شده است.
        /// </summary>
        public static string UserInRoleExisted {
            get {
                return ResourceManager.GetString("UserInRoleExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر اقدام کننده  با مالک رکورد همخوانی ندارد.
        /// </summary>
        public static string UserMatchingNotValid {
            get {
                return ResourceManager.GetString("UserMatchingNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر یافت نشد.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع کاربری معتبر نمی باشد.
        /// </summary>
        public static string UserTypeNotValid {
            get {
                return ResourceManager.GetString("UserTypeNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ والور از تاریخ روز جاری کوچکتر است.
        /// </summary>
        public static string ValurInOld {
            get {
                return ResourceManager.GetString("ValurInOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید تراکنش دو مرحله ای با شکست مواجه شد.
        /// </summary>
        public static string VerifyVoucherFailed {
            get {
                return ResourceManager.GetString("VerifyVoucherFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این صورتحساب مانده ندارد.
        /// </summary>
        public static string VoucherBalanceZero {
            get {
                return ResourceManager.GetString("VoucherBalanceZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعتبار این صورتحساب پایان پذیرفته است.
        /// </summary>
        public static string VoucherExpired {
            get {
                return ResourceManager.GetString("VoucherExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت صورتحساب با شکست مواجه شد.
        /// </summary>
        public static string VoucherFailed {
            get {
                return ResourceManager.GetString("VoucherFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صورتحساب یافت نشد.
        /// </summary>
        public static string VoucherNotFound {
            get {
                return ResourceManager.GetString("VoucherNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تناقض در مالکیت صورتحساب و صاحب کیف.
        /// </summary>
        public static string VoucherOwnerInValid {
            get {
                return ResourceManager.GetString("VoucherOwnerInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صورتحساب با موفقیت ثبت شد.
        /// </summary>
        public static string VoucherSuccessed {
            get {
                return ResourceManager.GetString("VoucherSuccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کیف مورد نظر یافت نشد.
        /// </summary>
        public static string WalletNotFound {
            get {
                return ResourceManager.GetString("WalletNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کیف پول پذیرنده یافت نشد.
        /// </summary>
        public static string WalletOfMerchantNotFount {
            get {
                return ResourceManager.GetString("WalletOfMerchantNotFount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سقف برداشت روزانه رعایت نشده است.
        /// </summary>
        public static string WithdrawDailyRejected {
            get {
                return ResourceManager.GetString("WithdrawDailyRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سقف برداشت ماهیانه رعایت نشده است.
        /// </summary>
        public static string WithdrawMonthlyRejected {
            get {
                return ResourceManager.GetString("WithdrawMonthlyRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سقف برداشت کل رعایت نشده است.
        /// </summary>
        public static string WithdrawTotalRejected {
            get {
                return ResourceManager.GetString("WithdrawTotalRejected", resourceCulture);
            }
        }
    }
}
