//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSHM.Presentation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSHM.Presentation.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسترسی شما محدود شده است.
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رابط کاربری با موفقیت متصل شد.
        /// </summary>
        public static string APIExecuted {
            get {
                return ResourceManager.GetString("APIExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اتصال رابط کاربری با شکست مواجه شد.
        /// </summary>
        public static string APIFailed {
            get {
                return ResourceManager.GetString("APIFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آواتار شما با موفقیت ثبت گردید.
        /// </summary>
        public static string AvatarChangeSuccess {
            get {
                return ResourceManager.GetString("AvatarChangeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شارژ تجمعی {0} تعداد از {1} ردیف کل با موفقیت انجام شد.
        /// </summary>
        public static string ChargeBatchSuccessed {
            get {
                return ResourceManager.GetString("ChargeBatchSuccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت نام غیرحضوری توسط ادمین سامانه بسته شده است.
        /// </summary>
        public static string CreationNewUserForbidden {
            get {
                return ResourceManager.GetString("CreationNewUserForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتقال اطلاعات بطور کامل انجام شد.
        /// </summary>
        public static string DataTransferCompletedSuccessfully {
            get {
                return ResourceManager.GetString("DataTransferCompletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غیر فعالسازی با موفقیت انجام شد.
        /// </summary>
        public static string Deactivation {
            get {
                return ResourceManager.GetString("Deactivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عبارت امنیتی نا معتبر است.
        /// </summary>
        public static string ErrorInCaptcha {
            get {
                return ResourceManager.GetString("ErrorInCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استثنای درونی در لایه مخزن بوجود آمده است.
        /// </summary>
        public static string ExceptionInRepositoryError605 {
            get {
                return ResourceManager.GetString("ExceptionInRepositoryError605", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد {0} باید {1} کاراکتر باشد.
        /// </summary>
        public static string FieldExactLengthNotMatch {
            get {
                return ResourceManager.GetString("FieldExactLengthNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکمیل فیلد {0} الزامی است.
        /// </summary>
        public static string FieldIsRequired {
            get {
                return ResourceManager.GetString("FieldIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول فیلد {0} نمی تواند از {1} کاراکتر بیشتر باشد.
        /// </summary>
        public static string FieldMaxLengthExceeded {
            get {
                return ResourceManager.GetString("FieldMaxLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار فیلد {0}  طبق فرمت معتبر نمی باشد.
        /// </summary>
        public static string FiledIsNotRegex {
            get {
                return ResourceManager.GetString("FiledIsNotRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داده‌های ورودی نامعتبر می‌باشد.
        /// </summary>
        public static string FormIsNotValid {
            get {
                return ResourceManager.GetString("FormIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرآیند استعلام با موفقیت انجام شد.
        /// </summary>
        public static string InquirySeccessed {
            get {
                return ResourceManager.GetString("InquirySeccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد امنیتی نا معتبر است.
        /// </summary>
        public static string InvalidCaptcha {
            get {
                return ResourceManager.GetString("InvalidCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هیچ رکوردی یافت نشد.
        /// </summary>
        public static string NotFoundAnyRecords {
            get {
                return ResourceManager.GetString("NotFoundAnyRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز پویا با موفقیت ایجاد شد.
        /// </summary>
        public static string OTPGenerated {
            get {
                return ResourceManager.GetString("OTPGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز پویا معتبر می باشد.
        /// </summary>
        public static string OTPIsValid {
            get {
                return ResourceManager.GetString("OTPIsValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز یکبار مصرف ارسال شد.
        /// </summary>
        public static string OTPSent {
            get {
                return ResourceManager.GetString("OTPSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گذرواژه با موفقیت تغییر یافت.
        /// </summary>
        public static string PasswordChanged {
            get {
                return ResourceManager.GetString("PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در تغییر گذرواژه.
        /// </summary>
        public static string PasswordChangeFiled {
            get {
                return ResourceManager.GetString("PasswordChangeFiled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روال ذخیره شده با موفقیت اجرا گردید.
        /// </summary>
        public static string ProcedureExecuted {
            get {
                return ResourceManager.GetString("ProcedureExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اجرای روال ذخیره شده با شکست مواجه گردید.
        /// </summary>
        public static string ProcedureFailed {
            get {
                return ResourceManager.GetString("ProcedureFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این رکورد تکراری می‌باشد.
        /// </summary>
        public static string RecordExisted {
            get {
                return ResourceManager.GetString("RecordExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این رکورد موجود نمی‌باشد.
        /// </summary>
        public static string RecordNotFound {
            get {
                return ResourceManager.GetString("RecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این رکورد موجود نمی‌باشد.
        /// </summary>
        public static string RecordNotFoundError610 {
            get {
                return ResourceManager.GetString("RecordNotFoundError610", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به لیست خطای پیوست مراجعه فرمایید.
        /// </summary>
        public static string ReferToErrorsList {
            get {
                return ResourceManager.GetString("ReferToErrorsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف رکورد با خطا مواجه گردید.
        /// </summary>
        public static string RemoveFailed {
            get {
                return ResourceManager.GetString("RemoveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف رکورد با موفقیت صورت پذیرفت.
        /// </summary>
        public static string RemoveSuccessed {
            get {
                return ResourceManager.GetString("RemoveSuccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر شناسه {0}  از سامانه {1}  به این گزارش دسترسی ندارد.
        /// </summary>
        public static string ReportAccessDenied {
            get {
                return ResourceManager.GetString("ReportAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اجرای گزارش با شکست مواجه گردید.
        /// </summary>
        public static string ReportFailed {
            get {
                return ResourceManager.GetString("ReportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازه زمانی گزارش تا یک ماه مجاز می باشد.
        /// </summary>
        public static string ReportFromToDateInInvalid {
            get {
                return ResourceManager.GetString("ReportFromToDateInInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش موردنظر ایجاد گردید.
        /// </summary>
        public static string ReportGenerated {
            get {
                return ResourceManager.GetString("ReportGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت رکورد با خطا مواجه گردید.
        /// </summary>
        public static string SaveFailed {
            get {
                return ResourceManager.GetString("SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت رکورد با موفقیت صورت پذیرفت.
        /// </summary>
        public static string SaveSuccessed {
            get {
                return ResourceManager.GetString("SaveSuccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کیف پول با موفقیت ایجاد گردید.
        /// </summary>
        public static string SaveSuccessedWallet {
            get {
                return ResourceManager.GetString("SaveSuccessedWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این رکورد با موفقیت و با شناسه {0} ثبت گردید.
        /// </summary>
        public static string SaveSuccessedWithID {
            get {
                return ResourceManager.GetString("SaveSuccessedWithID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلید کاربری به رایانامه و شماره همراه ارسال گردید.
        /// </summary>
        public static string SecretKeySent {
            get {
                return ResourceManager.GetString("SecretKeySent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عبارت امنیتی برای شماره همراه {0}  ارسال گردید.
        /// </summary>
        public static string SecurityCodeSendToCellphone {
            get {
                return ResourceManager.GetString("SecurityCodeSendToCellphone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این نوع سرور پیاده سازی نشده است.
        /// </summary>
        public static string ServerNotImplemented {
            get {
                return ResourceManager.GetString("ServerNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال پیامک با شکست مواجه شد.
        /// </summary>
        public static string SMSFailed {
            get {
                return ResourceManager.GetString("SMSFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیامک با موفقیت ارسال شد.
        /// </summary>
        public static string SMSSent {
            get {
                return ResourceManager.GetString("SMSSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تراکنش با موفقیت انجام شد.
        /// </summary>
        public static string TransactionSuccessed {
            get {
                return ResourceManager.GetString("TransactionSuccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مواجهه با یک استثنای ناشناخته.
        /// </summary>
        public static string UnknownException {
            get {
                return ResourceManager.GetString("UnknownException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش رکورد با خطا موجه گردید.
        /// </summary>
        public static string UpdateFailed {
            get {
                return ResourceManager.GetString("UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش رکورد با موفقیت صورت پذیرفت.
        /// </summary>
        public static string UpdateSuccessed {
            get {
                return ResourceManager.GetString("UpdateSuccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر یافت نشد.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رکورد انتخاب شده متعلق به این کاربر نمی باشد.
        /// </summary>
        public static string UserNotMathWithSelectedRecord {
            get {
                return ResourceManager.GetString("UserNotMathWithSelectedRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام سرور {0} | نام گزارش: {1}.
        /// </summary>
        public static string ValueServerAndReport {
            get {
                return ResourceManager.GetString("ValueServerAndReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید تراکنش دو مرحله ای با موفقیت انجام شد.
        /// </summary>
        public static string VerifyVoucherSuccessed {
            get {
                return ResourceManager.GetString("VerifyVoucherSuccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کیف پول با اطلاعات وارد شده معتبر می باشد.
        /// </summary>
        public static string WalletMatched {
            get {
                return ResourceManager.GetString("WalletMatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کیف پول با مشخصات فوق یافت نشد.
        /// </summary>
        public static string WalletNotMatched {
            get {
                return ResourceManager.GetString("WalletNotMatched", resourceCulture);
            }
        }
    }
}
